apiVersion: ENC[AES256_GCM,data:74o=,iv:DxnO8GzsWiphn/r1rMa7csiMkQfeiHnlkD26JsEbXO4=,tag:H0NcKLXmeLX8uInE76lgow==,type:str]
kind: ENC[AES256_GCM,data:h1ypRU8O,iv:vAnkBkAYZiIdQh00N/ogkkVPaWb+Ayjp12wn6jqtB2Q=,tag:DahRwCpIF3JhakIuXyJd/g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gGdSHzXdjadDMLlWDslWj78Rm/g=,iv:pdH42Ee29roO/DMy6KHFEp+7JyFz6t0Lmu48Qowhwnk=,tag:a3lVnNMYaGYPJ7Jedq8g6Q==,type:str]
    namespace: ENC[AES256_GCM,data:dwfgCFWmuLIdoP0=,iv:djImVwTuVJ7Bby6hFCZFkxfFwsxra2gb/rI/DxCAnlQ=,tag:p8N1abcsHjFCE5nHfSGfnw==,type:str]
type: ENC[AES256_GCM,data:yZtUWhRPXyI4EauxRUj9u0VSAzaPo6L9X+nmolIA,iv:A6z20gSO78j8uJzHWYmLOx0ieqps+YHnv3S60dodhZ4=,tag:Fk7qfww8FLZ7cbOkZbBqpw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:2wVLpB7w2SIUd+tuTtxGWqxBDezDMFjLLc0Evoa0Pfn4XwwWCt9HKcnks0Z1AoPIMRs22kH3QUkU0FJUbmrWky0FnQoqWJR8WDD+cvpu6m8dyayAHH0Pn4/4JDB0F38hmJ9uAmDe5iF56bNJ031eVVQ6qa0NGVDNh0V6BvXh9bJdqC3mh8l3m2hEAChGk0nu,iv:0ADdvD1sVNoFBpQ/xInAYS5aP9g2qDijvU1LfpXkdOk=,tag:HzZpz6dXkIXW0NKHkAAPHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pxs5rcmyaygpljvzftxggayw3h7d2a7mg6czl658vkyxtjaus59sysn3t3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OUh6dG5LVUpQZWxtZThp
            djA5cXNwY3pBMEEzSkZXZDRxVU90ZXgvUW04CjlVM3NCZVJvTFRUSy8ySjcxSWJj
            SlpnRE9sNHorT2V4N0J0RmRLeWZmcXMKLS0tIFNoYkR3cDV3VXptbnZkY2FDckp4
            ZTQ2aWhHU0cyQktQZ3U3OFFlN3FrRVkKI5N9mebn3HxPKZm8s1aUUA//y1N8MB3j
            cdwteC09vYXtaroffLIJsEWAxBqmGT83tKfjJRZJ/20mQcYBFCyFkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-31T20:53:47Z"
    mac: ENC[AES256_GCM,data:A+7MhgzUapSTRg8QojI7/1ZBl2BYfkw57tvT9wCLtfi7Acgn5VLVlzfT2QzuDOK5W3g0fn9VhtaJjQ8mVO+1rChcrGgK+HQFTIaXo0s42X+TCTQ00mBPZ/4Z9qGg/KyRDfX3NEJpT5w7MyrzO0VonJYr369QYxeZO4c4T9q4KYE=,iv:aeY7XvOB02p/h1mjiuFtMF7auR/ooXpDlQBdmXShPgA=,tag:3GjrmeGEuAPnS24zCqQnBg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
